[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ignored_warnings_from = ["lib/forge-std", "src/interfaces"]

evm_version = "cancun"
solc_version = "0.8.33"
via_ir = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
anvil = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# TODO: i want these ignored from src/interfaces, but thats not working apparently
[lint]
exclude_lints=["mixed-case-variable", "mixed-case-function"]
